//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by Wellington Vicioso on 4/30/17.
//  Copyright © 2017 Wellington Vicioso. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController, UITextFieldDelegate {
    
    @IBAction func handleChangeText(_ sender: UITextField) {
        //declare parameter as a dictionary which contains string as key and value combination. considering inputs are valid
        let input: String! = sender.text
        if input.characters.count > 2 {
            let dict = [
                "documents": [
                    [
                        "language": "en",
                        "id": "0",
                        "text": input
                    ]
                ]
            ] as [String: Any]
            if let jsonData = try? JSONSerialization.data(withJSONObject: dict) {
                let url = NSURL(string: "https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment")!
                let request = NSMutableURLRequest(url: url as URL)
                request.httpMethod = "POST"
                request.addValue("application/json", forHTTPHeaderField: "Content-Type")
                request.addValue("application/json", forHTTPHeaderField: "Accept")
                request.addValue("09179f3ca9324a7eb77fc85ea4a9e892", forHTTPHeaderField: "Ocp-Apim-Subscription-Key")
                request.httpBody = jsonData
                let task = URLSession.shared.dataTask(with: request as URLRequest){ data, response, error in
                    if error != nil{
                        print(error?.localizedDescription)
                        return
                    }
                    do {
                        let json = try JSONSerialization.jsonObject(with: data!, options: .mutableContainers) as? NSDictionary
                        let docs = json?["documents"] as! NSArray
                        let scoreAndId = docs[0] as! NSDictionary
                        let score = scoreAndId["score"] as! Float
                        if score != nil {
                            print("score")
                            DispatchQueue.main.async(execute: {
                                self.SentimentTracker.progress = score
                            })
                        }
                    } catch let error as NSError {
                        print(error)
                    }
                }
                task.resume()
            }
        }
    }
    
    @IBOutlet weak var SentimentTracker: UIProgressView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}
